# -*- coding: utf-8 -*-
"""Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0l6atajzvE4g3JdQRKnxgN5ol80dCi0

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('ToNY2')
banco.criar_conta('ToNY')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', -2)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('ronaldinho')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'ronaldinho', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', "-123")

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**  Trânsferência para conta inexistente
**Pré-condição:** Banco iniciar

**Passos:**  
1. Rodar o banco
2. entrar na conta
3. Transferir algum valor para outra conta não existente

**Resultado esperado:** ERRO - Conta destino não encontrada
**Resultado obtido:**  
ERRO -
**Status (Pass/Fail):** FAIL
**Evidência:**
ERRO - Conta destino não encontrada

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  Consulta de saldo para conta inexistente
**Pré-condição:**  Banco iniciar
**Passos:**  
1.  Entrar no banco
2.  Entrar na conta
3.  Consultar saldo
**Resultado esperado:**
ERRO
**Resultado obtido:**  
ERRO - Conta não encontrada: ronaldinho
**Status (Pass/Fail):**  
fail
**Evidência:**  
ERRO - Conta não encontrada: ronaldinho

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Depositar um valor 0
**Pré-condição:** Banco iniciar
**Passos:**  
1.  Iniciar o banco
2.  Entrar na conta
3.  Depositar valor
**Resultado esperado:**  
ERRO
**Resultado obtido:**  
OK - Depósito realizado: 0
**Status (Pass/Fail):**  
PASS
**Evidência:**  
OK - Depósito realizado: 0

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Teste N2 -  Depósito negativo como string
**Severidade (Baixa/Média/Alta):**  Baixa
**Prioridade (Baixa/Média/Alta):**  Baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O usuário consegue depositar valores mesmo sendo string

**Passos para reproduzir:**  
1.  banco rodando
2.  criar conta
3.  depositar

**Resultado esperado:** Depositra apenas >0 e como número
**Resultado obtido:** print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', "-123")

**Evidência:**  
banco.depositar('tony', "-123")

**Impacto/Risco:**  Impactos leve, não tem riscos que possam ser considerados gravissimos

## Template — Bug Report
**Título:**  Sistema aceita deposito de valores negativos
**Severidade (Baixa/Média/Alta):**  Alta
**Prioridade (Baixa/Média/Alta):**  alta
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  Quando inserido um valor de numero negativo o sistema deveria negar

**Passos para reproduzir:**  
1.  Iniciar banco
2.  entrar na conta
3.  Fazer depósito negativo

**Resultado esperado:**  
ERRO - Aceitamos apenas depositos positivos
**Resultado obtido:**  
OK - Depósito realizado: -2
**Evidência:**  
OK - Depósito realizado: -2
**Impacto/Risco:**  
impacto e risco alto

## Template — Bug Report
**Título:**  Sistema permite criar conta com números
**Severidade (Baixa/Média/Alta):**  baixa
**Prioridade (Baixa/Média/Alta):**  baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  SIstema permite que quando você crie uma conta também há possibilidade de colocar numeros

**Passos para reproduzir:**  
1.  Rodar banco
2.  Criar uma conta com nome e números

**Resultado esperado:**
ERRO - PARA CRIAR CONTA DIGITE APENAS LETRAS
**Resultado obtido:**  
OK - Conta criada para: ToNY2
**Evidência:**  
OK - Conta criada para: ToNY2
**Impacto/Risco:**  
Baixo

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""