# -*- coding: utf-8 -*-
"""QA_Banco_Stark_SN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6pwi3dYRBS8zHrfppnYTdDqdrdqqZqB

Criação de Classe - Classe CONTA
"""

class Conta:
    def __init__(self, titular):
        self.titular = titular
        self.saldo = 0
        self.extrato = []

print('Classe Conta criada')

"""Criação do BCO"""

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return
        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

    def depositar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito',valor))

        print('Depósito realizado:',valor)

    def sacar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        if self.contas[titular].saldo < valor:
            print('Saldo insuficiente')
            return

        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque',valor))

        print('Saque realizado:',valor)

    def saldo(self, titular):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        print('Saldo de', titular, '=', self.contas[titular].saldo)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

print('Operações adicionadas')

"""Rodando o SISTEMA"""

banco = BancoDoStark()
print('Sistema do Banco Stark iniciado')

"""Caminho FELIZ"""

banco.criar_conta('Tony Stark')

banco.depositar('Tony Stark', 100000)

banco.saldo('Tony Stark')

banco.sacar('Tony Stark', 89000)

banco.saldo('Tony Stark')

banco.criar_conta('Steve Rogers')
banco.criar_conta('Bruce Banner')
banco.criar_conta('Thor')
banco.criar_conta('Natasha Romanoff')

banco.depositar('Steve Rogers', 50000)
banco.depositar('Bruce Banner', 1000)
banco.depositar('Thor', 10000)
banco.depositar('Natasha Romanoff', 59000)

banco.sacar('Bruce Banner', 200)
banco.sacar('Thor', 120)
banco.sacar('Natasha Romanoff', 1000)

banco.saldo('Tony Stark')
banco.saldo('Steve Rogers')
banco.saldo('Bruce Banner')
banco.saldo('Thor')
banco.saldo('Natasha Romanoff')

"""Teste Negativo - QA"""

banco.criar_conta('Tony Stark')

banco.criar_conta('123456789')

banco.depositar('Tony Stark', -500)

banco.sacar('Tony Stark', -15000)

banco.depositar('Tony Stark', 0)

banco.depositar('Bruce Banner', 999999999999999999999999999999999999999999999999999999999)

banco.depositar('Bruce Banner', Mil Reais)

banco.criar_conta('')

banco.criar_conta('TONY STARK')

banco.depositar('TONY STARK', 0.0001)

"""Novo módulo de Transferências

Caminho Feliz
"""

banco.transferir('Tony Stark', 'Steve Rogers', 1000)

banco.transferir('Tony Stark', 'Bruce Banner', 1000000000000000000000)

"""Teste Negativo - QA"""

banco.transferir('Tony Stark', 'Bruce Banner', -1000)

banco.transferir('Tony Stark', 'Bruce Banner', 0)

banco.transferir('Tony Stark', 'Bruce Banner', 99999999999999999999999999999999999)