# -*- coding: utf-8 -*-
"""Ailton Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kixvCFQ_g7VQsaWyEnxNLZVLjftWaKUS

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('steve')
banco.criar_conta('carter')
banco.criar_conta('buck')

print('\n=== DEPÓSITOS ===')
banco.depositar('steve', 5000)
banco.depositar('carter', 2000)

print('\n=== SALDOS ===')
banco.saldo_atual('steve')
banco.saldo_atual('carter')

print('\n=== SAQUE ===')
banco.sacar('steve', 1000)
banco.saldo_atual('steve')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('steve', 'carter', 500)
banco.saldo_atual('steve')
banco.saldo_atual('carter')

print('\n=== EXTRATO (steve) ===')
banco.mostrar_extrato('steve')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('steve', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('steve', -2000)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('steve')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('steve', 500000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('steve', 'tchalla', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('peter')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('peter')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**Criação de Conta  
**Pré-condição:**Sistema do banco iniciado.

**Passos:**  
1.Rodar o banco
2.banco.criar_conta('steve')

**Resultado esperado:**O sistema deve criar a conta informada e registrar no banco.
**Resultado obtido:** A conta foi criada com sucesso.
**Status (Pass/Fail):** Pass
**Evidência:**=== CRIAR CONTAS ===
OK - Conta criada para: steve

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Realizar depósito em conta existente
**Pré-condição:** Conta "steve" já criada.
**Passos:**  
1. banco.depositar('steve', 5000)
2. banco.saldo_atual()

**Resultado esperado:** O sistema deve realizar o depósito e atualizar o saldo.
**Resultado obtido:** O depósito foi realizado e o saldo atualizado.
**Status (Pass/Fail):** Pass
**Evidência:**  === DEPÓSITO ===
OK - Depósito realizado: 5000

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:** Realizar transferência entre contas existentes
**Pré-condição:** Conta "steve" criada com saldo suficiente e conta "carter" existente.
**Passos:**  
1. Executar banco.transferir('steve', 'carter', 500)
2. Consultar saldo de steve
3. Consultar saldo de carter
**Resultado esperado:** O sistema deve transferir 500 da conta "steve" para "carter", atualizando os dois saldos.
**Resultado obtido:** A transferência foi realizada e os saldos atualizados corretamente.
**Status (Pass/Fail):** Pass
**Evidência:**  === TRANSFERÊNCIA ===
Transferência realizada: 500
Saldo steve atualizado
Saldo carter atualizado

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Teste N1 - Consulta de saldo para conta inexistente não é tratada corretamente
**Severidade (Baixa/Média/Alta):**  Média
**Prioridade (Baixa/Média/Alta):**  Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
Ao tentar consultar o saldo de uma conta que não existe no sistema, o sistema não trata corretamente a situação ou não exibe uma mensagem de erro.

**Passos para reproduzir:**  
1.  banco rodando
2.  Não criar a conta peter
3.  Executar banco.saldo_atual('peter')

**Resultado esperado:** O sistema deve informar que a conta não existe.
**Resultado obtido:**  O sistema tenta realizar a consulta mesmo sem a conta existir ou não apresenta mensagem de erro.
**Evidência:**  Teste N5 - Consulta de conta inexistente (saldo)
Conta: peter
**Impacto/Risco:**  Pode gerar confusão para o usuário e falta de validação de dados no sistema.

## Template — Bug Report
**Título:** Sistema aceita depósito com valor negativo
**Severidade (Baixa/Média/Alta):** Alta
**Prioridade (Baixa/Média/Alta):** Alta
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O sistema permite realizar depósito com valor negativo, o que pode não fazer sentido no saldo.
**Passos para reproduzir:**  
1. Criar conta steve
2. Executar banco.depositar('steve', -2000)

**Resultado esperado:** O sistema deve bloquear valores negativos.
**Resultado obtido:** O sistema aceita o valor negativo.
**Evidência:** Teste N2 - Depósito negativo
OK - Depósito realizado: -2000
**Impacto/Risco:** Pode manipular errado o saldo da conta.

## Template — Bug Report
**Título:** Transferência para conta inexistente não é bloqueada corretamente
**Severidade (Baixa/Média/Alta):** Média
**Prioridade (Baixa/Média/Alta):** Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O sistema permite tentar realizar transferência para uma conta que não existe.

**Passos para reproduzir:**  
1. Criar conta steve
2. Depositar saldo
3. Executar banco.transferir('steve', 'tchalla', 50)

**Resultado esperado:** O sistema deve impedir a transferência e informar que a conta destino não existe.
**Resultado obtido:** A operação é executada ou não retorna erro.
**Evidência:** Teste N4 - Transferência para conta inexistente
Conta destino: tchalla
**Impacto/Risco:** Pode causar perda de dados ou erro nas transações.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""