# -*- coding: utf-8 -*-
"""Amanda_Brito-ADS5NB_QA_Banco_do_Stark

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5G090MFqTAfVBDCcaRe-bSKZ9G-8QH1

# Atividade em Aula — QA Manual (Partes 04 e 05)
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste (Parte 04)**
- Registrar pelo menos **1 Bug Report profissional (Parte 05)**

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""## Execução guiada (base para a atividade)
Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa (Partes 04 e 05) será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('luan')
banco.criar_conta('rafael')
banco.criar_conta('santana')

print('\n=== DEPÓSITOS ===')
banco.depositar('luan', 100000)
banco.depositar('rafael', 5000)

print('\n=== SALDOS ===')
banco.saldo_atual('santana')
banco.saldo_atual('rafael')

print('\n=== SAQUE ===')
banco.sacar('luan', 200)
banco.saldo_atual('luan')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('luan', 'rafael', 100)
banco.saldo_atual('luan')
banco.saldo_atual('rafael')

print('\n=== EXTRATO (luan) ===')
banco.mostrar_extrato('luan')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('luan', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('luan', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('luan')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('luan', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('luan', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('jade')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('jade')

print('\nTeste N7 - Transferência de uma conta sem saldo')
banco.transferir('santana', 'rafael', 50)

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:** Depósito negativo  
**Pré-condição:**  Inserir valor negativo
**Passos:**  
1.  digitar uma conta
2.  incluir um valor negativo
3.  executar

**Resultado esperado:**  ERRO Insira um valor maior que 0

**Resultado obtido:**  OK - Depósito realizado: -100

**Status (Pass/Fail):**  Fail

**Evidência:**  Teste N2 - Depósito negativo
OK - Depósito realizado: -100

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  Consulta de saldo de conta inexistente

**Pré-condição:**  Não criar a conta

**Passos:**  
1.  Inserir código de consulta
2.  Inserir uma conta inexistente no código
3.  Executar

**Resultado esperado:** ERRO - Conta não encontrada: jade

**Resultado obtido:**  ERRO - Conta não encontrada: jade

**Status (Pass/Fail):**  Pass

**Evidência:**  Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: jade

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Transferência de uma conta sem saldo

**Pré-condição:**  Valor de trasnferencia maior do que o saldo da conta

**Passos:**  
1.  Criar contas
2.  Realizar transação de uma conta sem saldo
3.  Executar

**Resultado esperado:**  ERRO - Saldo insuficiente

**Resultado obtido:**  ERRO - Saldo insuficiente

**Status (Pass/Fail):**  Pass

**Evidência:**  Teste N7 - Transferência de uma conta sem saldo
ERRO - Saldo insuficiente

# PARTE 05 — Bug Report (atividade)
Agora escolha **1 falha** que você observou e registre um **Bug Report profissional**.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Depósito negativo

**Severidade (Baixa/Média/Alta):**  Média

**Prioridade (Baixa/Média/Alta):**  Média

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  Realisar um depósito de um valor negativo em uma conta existente

**Passos para reproduzir:**  
1.  digitar uma conta
2.  incluir um valor negativo
3.  executar

**Resultado esperado:**  ERRO Insira um valor maior que 0

**Resultado obtido:**  OK - Depósito realizado: -100

**Evidência:**  Teste N2 - Depósito negativo OK - Depósito realizado: -100

**Impacto/Risco:**  O depósito de valores negativos pode ser usado como uma forma de golpe e fraude, já que o detalhe do carcter - pode passar despercebidono momento de uma compra, por exemplo

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""