# -*- coding: utf-8 -*-
"""atividade_qa_banco_do_stark_joao_vitor_pereira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PijHRfLcAkFRf1gP99cyHgUH0bJV45L
"""

class Conta:
    def __init__(self, titular):
        self.titular = titular
        self.saldo = 0
        self.extrato = []

print('Classe Conta criada')

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return
        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

    def depositar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito',valor))

        print('Depósito realizado:',valor)

    def sacar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        if self.contas[titular].saldo < valor:
            print('Saldo insuficiente')
            return

        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque',valor))

        print('Saque realizado:',valor)

    def saldo(self, titular):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        print('Saldo de', titular, '=', self.contas[titular].saldo)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

print('Operações adicionadas')

banco = BancoDoStark()
print('Sistema do Banco Stark iniciado')

banco.criar_conta('')

banco.criar_conta('Capitão América')

banco.sacar('Capitão América', -20000)

banco.depositar('Capitão América', 0)

"""Template — Caso de Teste 1
ID: CT-001
Título/Objetivo: Criar conta sem nome
Pré-condição: Ter o banco
Passos:Usar a função criar conta e deixar o nome da conta vazio

Resultado esperado: Sistema não permitir que uma conta sem nome seja cirada
Resultado obtido: Sistema permitiu a conta ser cirada
Status (Pass/Fail): Fail
Evidência:
banco.criar_conta('')
Conta criada para

Template — Caso de Teste 2
ID: CT-002
Título/Objetivo: Saque negativo
Pré-condição: ter uma conta criada
Passos: realizar um saque negativa em uma conta

Resultado esperado: Erro
Resultado obtido: Saque realizado
Status (Pass/Fail): Fail
Evidência: banco.sacar('Capitão América', -20000)

Saque realizado: -20000

Template — Caso de Teste 3
ID: CT-003
Título/Objetivo: Depóstio com valor 0
Pré-condição: ter uma conta
Passos: usar a função de depositar com o valor 0

Resultado esperado: Erro
Resultado obtido: Depósito realizado
Status (Pass/Fail): Fail
Evidência: banco.depositar('Capitão América', 0)
Depósito realizado: 0

Template — Bug Report
Título: Saque negativo
Severidade (Baixa/Média/Alta): Alta
Prioridade (Baixa/Média/Alta): Alta
Ambiente: Google Colab / Python 3.x / Banco do Stark

Descrição: o usuário pode realizar um saque com valor negativo

Passos para reproduzir: usar a função saque e digitar um valor negativo

Resultado esperado: Erro
Resultado obtido: Saque realizado
Evidência:
banco.sacar('Capitão América', -20000)
Saque realizado: -20000
Impacto/Risco: Pode causar inconsistência nos saldos das contas e permitir manipulação indevida de valores no sistema bancário.
"""