# -*- coding: utf-8 -*-
"""Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0l6atajzvE4g3JdQRKnxgN5ol80dCi0

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('Tony')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**  Depositar valor conta
**Pré-condição:** Conta destinada ter que existir

**Passos:**  
1. banco.criar_conta('NomeDaConta')
2. banco.depositar('NomeDaConta', valor)

**Resultado esperado:** OK - Depósito realizado: valor
**Resultado obtido:**  OK - Depósito realizado: 1000
**Status (Pass/Fail):** Pass
**Evidência:**
=== DEPÓSITOS ===
OK - Depósito realizado: 1000
OK - Depósito realizado: 500

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Sacar valor de conta

**Pré-condição:**  Conta existir e ter o valor em conta

**Passos:**  
1. banco.criar_conta('NomeDaConta')
2. banco.depositar('NomeDaConta', valor)
3. banco.sacar('NomeDaConta', valor)
4. banco.saldo_atual('Nome da Conta')

**Resultado esperado:**

OK - Saque realizado: valor

SALDO NomeDaConta: novoValor

**Resultado obtido:**  

**Status (Pass/Fail):**  Pass

**Evidência:**  
=== SAQUE ===

OK - Saque realizado: 200

SALDO tony = 3200.0

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Transferir valor entre contas

**Pré-condição:**  Ter duas contas criadas e a de destino possuir saldo

**Passos:**  
1.  banco.criar_conta('NomeDaConta')
2.  banco.depositar('NomeDaConta', valor)
3.  banco.transferir('ContaOrigem', 'ContaDestino', valor)

**Resultado esperado:** OK - Transferência realizada: valor  

**Resultado obtido:**  
=== TRANSFERÊNCIA ===

OK - Transferência realizada: 100

SALDO tony = 3100.0

SALDO pepper = 3000.0

**Status (Pass/Fail):**  Pass

**Evidência:**  
=== TRANSFERÊNCIA ===

OK - Transferência realizada: 100

SALDO tony = 3100.0

SALDO pepper = 3000.0

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Deposito = 0

**Severidade (Baixa/Média/Alta):**  baixa

**Prioridade (Baixa/Média/Alta):**  baixa

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O sistema permite a realização de depósitos com valor igual a zero

**Passos para reproduzir:**  
1.  Criar conta - banco.criar_conta('NomeDaConta')
2.  Inserir valor zero como deposito - banco.depositar('NomeDaConta', valor)

**Resultado esperado:**
- Mensagem de erro: "ERRO - insira um valor de deposito maior que 0.0"

**Resultado obtido:**
- OK - Depósito realizado: 0

**Evidência:**  
- OK - Depósito realizado: 0

**Impacto/Risco:**
Baixo

## Template — Bug Report
**Título:**  Sistema aceita depósito com valor negativo

**Severidade (Baixa/Média/Alta):**  Alta

**Prioridade (Baixa/Média/Alta):**  Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  

**Passos para reproduzir:**  

1. Criar uma conta - banco.criar_conta('tony')

2. Verificar saldo inicial (ex: 1000)

3. Realizar um depósito com valor negativo - banco.depositar('tony', -100)

4. Verificar saldo após operação



**Resultado esperado:**  
- Mensagem de erro: "ERRO - Valor de depósito deve ser maior que zero"

**Resultado obtido:**  
- OK - Depósito realizado: -100

- Saldo é reduzido em 100 (de 1000 para 900)

**Evidência:**  

Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 900.0

**Impacto/Risco:**  

Alto

## Template — Bug Report
**Título:**  Case sensitivity na consulta de contas causa inconsistência
**Severidade (Baixa/Média/Alta):**  Média
**Prioridade (Baixa/Média/Alta):**  Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O sistema diferencia maiúsculas de minúsculas ao buscar contas, causando confusão no usuário

**Passos para reproduzir:**  
1.  Criar uma conta - banco.criar_conta('tony')
2. Consultar saldo usando variação com maiúscula - banco.saldo_atual('Tony')  

**Resultado esperado:**  

Sistema encontrar a conta independente do case sensitive.

**Resultado obtido:**
ERRO - Conta não encontrada: Tony

Mesmo que a conta 'tony' exista no sistema

**Evidência:**

Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: Tony

**Impacto/Risco:**
Médio

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""