# -*- coding: utf-8 -*-
"""Lucas da Silva Fernandes_106419_atividade_qa_banco_do_stark.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idzSPlAPKg1kDKyGj-CRoy9tOCLyK089
"""

class Conta:
    def __init__(self, titular):
        self.titular = titular
        self.saldo = 0
        self.extrato = []

print('Classe Conta criada')

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return
        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

    def depositar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito',valor))

        print('Depósito realizado:',valor)

    def sacar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        if self.contas[titular].saldo < valor:
            print('Saldo insuficiente')
            return

        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque',valor))

        print('Saque realizado:',valor)

    def saldo(self, titular):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        print('Saldo de', titular, '=', self.contas[titular].saldo)

print('Operações adicionadas')

banco = BancoDoStark()
print('Sistema do Banco Stark iniciado')

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('Tony')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo: Criar conta já existente**    
**Pré-condição: ter uma conta existente**

**Passos:**  
1. ter uma conta existente
2. criar uma nova com o mesmo nome

**Resultado esperado: A criação da conta deve ser bloqueado**
**Resultado obtido: Criação bloaqueada**  
**Status (Pass/Fail): PASS**
**Evidência: ERRO - Conta já existe: tony**

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:Transferência para conta inexistente**  
**Pré-condição: ter uma conta existente**  
**Passos:**  
1.  Ter uma conta existente
2.  Relaizar a tranferência para uma conta que não existe
**Resultado esperado: Tranferência não ser realizada**  
**Resultado obtido:Tranferência não ser realizada**  
**Status (Pass/Fail):Pass**  
**Evidência:Teste N4 - Transferência para conta inexistente
ERRO - Conta destino não encontrada**

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo: Saque acima do saldo**  
**Pré-condição: Ter uma conta existem com saldo disponível**
**Passos:**  
1.ter uma conta existente
2.realizar o saque  
3.
**Resultado esperado: Impedir o saque devido o saldo baixo**  
**Resultado obtido: saque impedido**  
**Status (Pass/Fail):Pass**  
**Evidência:Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente**

## Template — Bug Report
**Título:Sistema aceita depósito com valor negativo**  
**Severidade (Baixa/Média/Alta):Alta**  
**Prioridade (Baixa/Média/Alta):Média**  
**Ambiente:** Google Colab

**Descrição: testar se o usuário tem a capacidade de realizar um deposito com o valor negativo**  

**Passos para reproduzir:**  
1.Ter uma conta existente  
2.Realizar um deposito  
3.Realizar o deposito com o valor menor que zero  

**Resultado esperado: O deposito deve ser cancelado**  
**Resultado obtido:Deposito negativo realizado**  
**Evidência:Teste N2 - Depósito negativo
OK - Depósito realizado: -100**  
**Impacto/Risco: Caso continue assim o usuário pode subtarir o valor de sua conta com o depósiro ao invez de somar**

## Template — Bug Report
**Título:Sistema aceita depósito com valor 0**  
**Severidade (Baixa/Média/Alta):Alta**  
**Prioridade (Baixa/Média/Alta):Média**  
**Ambiente:** Google Colab

**Descrição: testar se o usuário tem a capacidade de realizar um deposito com o valor 0**  

**Passos para reproduzir:**  
1.Ter uma conta existente  
2.Realizar um deposito  
3.Realizar o deposito com o valor zero  

**Resultado esperado: O deposito deve ser cancelado**  
**Resultado obtido:Deposito com valor 0 realizado**  
**Evidência:Teste Evidência: OK - Depósito realizado: 0***  
**Impacto/Risco: Caso continue assim o usuário pode realizar depositos sem valor**

## Template — Bug Report
**Título:Permitir a tranferência para a mesma conta**  
**Severidade (Baixa/Média/Alta):Média**  
**Prioridade (Baixa/Média/Alta):Média**  
**Ambiente:** Google Colab

**Descrição: testar se o usuário tem a capacidade de realizar uma tranferência para a sua própria conta**

**Passos para reproduzir:**  
1.Ter uma conta existente  
2.Ter saldo
3.Realizar uma tranferência para a mesma conta  

**Resultado esperado: A tranferência deve ser cancelado**  
**Resultado obtido:Tranferência realizada**  
**Evidência:OK - Transferência realizada: 100***  
**Impacto/Risco: Caso continue assim o usuário pode realizar tranferências sem sendido**
"""

banco.transferir('tony', 'tony', 100)