# -*- coding: utf-8 -*-
"""Cópia de atividade_qa_partes_04_05_banco_do_stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ca_FLKje8Wze-cf64M3spxxA08bPdJiC

# Atividade em Aula — QA Manual (Partes 04 e 05)
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste (Parte 04)**
- Registrar pelo menos **1 Bug Report profissional (Parte 05)**

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""## Execução guiada (base para a atividade)
Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa (Partes 04 e 05) será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:** Validar se o sistema rejeita depósitos com valor zero.
**Pré-condição:**  Conta do titular 'tony' criada e ativa no sistema.
**Passos:**  
1. Iniciar o sistema do banco.
2. Acionar o método de depósito para a conta alvo usando o valor 0: banco.depositar('tony', 0).
3. Verificar a mensagem de retorno no terminal e o saldo atualizado.

**Resultado esperado:** O sistema deve bloquear a operação informando que o depósito precisa ser maior que zero, e o saldo não deve ser alterado.

**Resultado obtido:**  O sistema aceitou a operação e exibiu a mensagem "OK - Depósito realizado: 0".

**Status (Pass/Fail):** Fail

**Evidência:** > Teste N1 - Depósito com valor zero

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Validar se o sistema impede saques com valor superior ao saldo atual da conta.  
**Pré-condição:** Conta do titular 'tony' possui um saldo de 600.0.
**Passos:**  
1. Consultar o saldo atual para garantir que é menor que o valor a ser sacado.
2. Acionar o método de saque com um valor superior ao saldo: banco.sacar('tony', 100000).
3. Verificar a saída no console.

**Resultado esperado:** A operação deve ser negada com uma mensagem de "Saldo insuficiente" e o saldo da conta deve permanecer inalterado (600.0).

**Resultado obtido:** A operação foi corretamente bloqueada com a mensagem de erro apropriada.

**Status (Pass/Fail):** Pass

**Evidência:** > Teste N3 - Saque acima do saldo

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:** Validar o comportamento do sistema ao tentar transferir valores para uma conta de destino que não está cadastrada.  
**Pré-condição:** Conta de origem 'tony' criada e com saldo positivo. Conta de destino 'thor' não existe no banco.  
**Passos:**  
1. Confirmar que a conta origem possui saldo suficiente.
2. Executar a função de transferência apontando para o destinatário inválido: banco.transferir('tony', 'thor', 50).
3. Verificar a validação de contas na saída do terminal.

**Resultado esperado:** O sistema deve identificar que o destinatário não existe, cancelar a transação, manter o saldo da origem intacto e exibir uma mensagem de erro ("Conta destino não encontrada").

**Resultado obtido:** A transação foi bloqueada corretamente apontando a ausência da conta de destino.

**Status (Pass/Fail):** Pass  
**Evidência:** > Teste N4 - Transferência para conta inexistente

# PARTE 05 — Bug Report (atividade)
Agora escolha **1 falha** que você observou e registre um **Bug Report profissional**.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:** Sistema aceita depósitos com valores negativos e subtrai indevidamente o valor do saldo do cliente

**Severidade (Baixa/Média/Alta):** Alta (Compromete o cálculo do saldo, funcionalidade principal da aplicação).

**Prioridade (Baixa/Média/Alta):** Alta (Necessita correção imediata para evitar manipulação de fundos).

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** Durante a execução de testes negativos, observou-se que a função depositar() não possui validação de valor mínimo. Se um usuário inserir um valor negativo, o Python executa a operação de soma algébrica (saldo += valor), resultando em uma subtração do saldo. O sistema processa a falha silenciosamente e ainda a registra como um "Depósito realizado".

**Passos para reproduzir:**  
1. Instanciar a classe BancoDoStark.
2. Criar uma conta chamando banco.criar_conta('tony').
3. Realizar um depósito inválido passando um número negativo: banco.depositar('tony', -100).
4. Consultar o saldo atual e o extrato da conta.

**Resultado esperado:** A regra de negócios (Requisito 2) determina que depósitos devem ter valor > 0. O sistema deveria abortar a função, exibir um erro "Valor inválido" e o saldo da conta não deveria ser impactado.

**Resultado obtido:** A operação passa direto, imprimindo sucesso, e o valor é retirado da conta do cliente.

**Evidência:**  
**Impacto/Risco:** Risco altíssimo de integridade financeira. Permite que um usuário comum utilize a rota de depósito para efetuar saques arbitrários disfarçados, quebrando totalmente a confiabilidade do banco e o controle de extrato.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

print('\n=================================')
print('TESTES ADICIONAIS (QA - Opcional)')
print('=================================\n')

# 1. Testar criação de conta com nome vazio (Regra 1: Titular não pode ser vazio)
print('Teste N7 - Criar conta com nome vazio ou apenas espaços')
banco.criar_conta('')
banco.criar_conta('   ')

# 2. Testar saque com valor zero ou negativo (Regra 3: Saque deve ser > 0)
print('\nTeste N8 - Saque com valor zero')
banco.sacar('pepper', 0)

print('\nTeste N9 - Saque com valor negativo (Tentativa de injetar saldo)')
banco.saldo_atual('pepper') # Saldo antes
banco.sacar('pepper', -500)
banco.saldo_atual('pepper') # Saldo depois

# 3. Testar transferência para si mesmo (Regra 4: Não pode transferir para si mesmo)
# Vamos primeiro adicionar um saldo para o banner poder testar
banco.depositar('banner', 1000)
print('\nTeste N10 - Transferência para a própria conta')
banco.transferir('banner', 'banner', 100)
banco.mostrar_extrato('banner')

# 4. Testar transferência com valor negativo (Regra 4: Transferência deve ser > 0)
print('\nTeste N11 - Transferência com valor negativo (Roubo de saldo?)')
banco.transferir('banner', 'pepper', -200)
banco.saldo_atual('banner')
banco.saldo_atual('pepper')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""