# -*- coding: utf-8 -*-
"""Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0l6atajzvE4g3JdQRKnxgN5ol80dCi0

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta(123)
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', -100)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'ronaldo', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('Tony')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
ID: CT-001  
Título/Objetivo: Verificar se é possível criar contas utilizando apenas números no campo nome.

Pré-condição:
- Sistema iniciado e banco de dados ativo.

Passos:
1. Ativar o banco de dados.
2. Remover as aspas do campo nome.
3. Digitar o valor 123 no campo nome.
4. Tentar criar a conta.

Resultado esperado:
O sistema deve retornar um erro informando que o nome da conta deve conter caracteres válidos (não apenas números).

Resultado obtido:
ERRO - Conta já existe: 123

Status (Pass/Fail): Pass

Evidência:
=== CRIAR CONTAS ===  
ERRO - Conta já existe: 123

## Template — Caso de Teste 2
ID: CT-002  
Título/Objetivo: Validar se é possível realizar um depósito com valor negativo.

Pré-condição:
- Sistema iniciado e banco de dados ativo.
- Conta previamente cadastrada.

Passos:
1. Iniciar o banco.
2. Selecionar a opção de depósito.
3. Digitar um valor negativo.
4. Executar a operação.

Resultado esperado:
O sistema deve impedir a operação e exibir uma mensagem de erro informando que não é permitido realizar depósitos com valores negativos.

Resultado obtido:
=== DEPÓSITOS ===  
OK - Depósito realizado: -100

Status (Pass/Fail): Fail

Evidência:
=== DEPÓSITOS ===  
OK - Depósito realizado: -100

## Template — Caso de Teste 3

**ID:** CT-003  
**Título/Objetivo:** Verificar se é possível realizar uma transferência para uma conta que não existe.

**Pré-condição:**  
- Banco iniciado.  
- Usuário autenticado em uma conta válida.  
- Opção de transferência disponível.

**Passos:**  
1. Iniciar o banco.  
2. Realizar login em uma conta pré-existente.  
3. Informar uma conta de destino que não existe.  
4. Tentar realizar a transferência.

**Resultado esperado:**  
O sistema deve impedir a operação e exibir uma mensagem informando que a conta de destino não foi encontrada.

**Resultado obtido:**  

=== TRANSFERÊNCIA ===
ERRO - Conta destino não encontrada

**Status (Pass/Fail):** Fail  

**Evidência:**  

=== TRANSFERÊNCIA ===
ERRO - Conta destino não encontrada

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:** Sistema aceita depósito com valor zero

**Severidade:** Média  
**Prioridade:** Alta  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O sistema permite realizar depósitos com valor **0**, porém o valor deveria ser **maior que zero**.

**Passos para reproduzir:**  
1. Criar uma conta: banco.criar_conta('tony')  
2. Realizar depósito com valor zero: banco.depositar('tony', 0)  
3. Verificar o saldo: banco.saldo_atual('tony')  
4. Verificar o extrato: banco.mostrar_extrato('tony')

**Resultado esperado:**  
O sistema deve impedir o depósito e exibir mensagem de erro informando que o valor deve ser maior que zero.

**Resultado obtido:**  

OK - Depósito realizado: 0


**Impacto/Risco:**  
Operações inválidas podem ser registradas no extrato.

**Evidência:**  

Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

## Template — Bug Report
**Título:** Extrato registra depósitos com valores inválidos

**Severidade:** Média  
**Prioridade:** Alta  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark

**Descrição:**  
O sistema registra no extrato depósitos com valores **zero e negativos**, que deveriam ser rejeitados. O extrato deveria conter apenas operações válidas.

**Passos para reproduzir:**  
1. Criar uma conta: `banco.criar_conta('tony')  
2. Realizar depósitos:  
   -banco.depositar('tony', 1000)  
   -banco.depositar('tony', 0)  
   -banco.depositar('tony', -100)  
3. Verificar o extrato: `banco.mostrar_extrato('tony')

**Resultado esperado:**  
O extrato deve registrar apenas operações válidas.

**Resultado obtido:**  

('deposito', 1000)
('deposito', 0)
('deposito', -100)


**Impacto/Risco:**  
O extrato pode registrar operações inválidas, prejudicando auditorias e relatórios.

**Evidência:**  

=== EXTRATO (tony) ===
EXTRATO: tony
 - ('deposito', 1000)
 - ('saque', 200)
 - ('transferencia_saida', 100)
 - ('deposito', 0)
 - ('deposito', -100)

## Template — Bug Report
**Título:** Sistema permite transferência para a mesma conta

**Severidade:** Média  
**Prioridade:** Alta  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark

**Descrição:**  
O sistema não valida se a conta de origem é igual à conta de destino. Isso permite que um usuário realize uma transferência para si mesmo, o que é uma operação inválida segundo as regras do sistema.

**Passos para reproduzir:**  
1. Criar uma conta: banco.criar_conta('tony')`  
2. Realizar um depósito: banco.depositar('tony', 1000)`  
3. Verificar saldo inicial: banco.saldo_atual('tony')`  
4. Tentar transferir para si mesmo: banco.transferir('tony', 'tony', 100)`  
5. Verificar saldo final: banco.saldo_atual('tony')`  
6. Verificar extrato: banco.mostrar_extrato('tony')`

**Resultado esperado:**  
O sistema deve impedir a operação e exibir erro informando que não é permitido transferir para a mesma conta.

**Resultado obtido:**  

OK - Transferência realizada: 100


**Impacto/Risco:**  
Operações sem sentido podem ser registradas no extrato, poluindo o histórico de transações.

**Evidência:**  

banco.transferir('tony', 'tony', 100)
OK - Transferência realizada: 100

SALDO tony = 1000

EXTRATO: tony
 - ('deposito', 1000)
 - ('transferencia_saida', 100)
 - ('transferencia_entrada', 100)

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""