# -*- coding: utf-8 -*-
"""Cópia de Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivFJUbrKZy4gjoMJcUmG1XxGz4PEc1jI

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')



"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**   CRIAR CONTAS
**Pré-condição:** Banco Iniciado

**Passos:**  
1. Iniciar o Banco
2. banco.criarconta('Nome")

**Resultado esperado:** OK - Conta criada para: Nome
**Resultado obtido:**  OK - Conta criada para: Nome
**Status (Pass/Fail):**
**Evidência:**

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  Depositar valor negativo
**Pré-condição:**  banco deve estar iniciado, ter 1 conta e a função depoistar da classe banco estar funcionando
**Passos:**  
1.  iniciar o banco
2.  criar conta
3.  depositar numero negativo
**Resultado esperado:**  fail - não pode depositar valor negativo
**Resultado obtido:**   pass - sem erro aparente
**Status (Pass/Fail):**  Pass
**Evidência:**  Teste N2 - Depósito negativo
OK - Depósito realizado: -100

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Sacar acima do saldo
**Pré-condição:**  banco iniciado e ter uma conta
**Passos:**  
1.  inibiar banco
2.  criar conta
3.  sacar valor maior do que o que tem na conta
**Resultado esperado:**  fail - saque acima do saldo
**Resultado obtido:**  fail - saque acima do saldo
**Status (Pass/Fail):**  fail
**Evidência:**  
Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Teste N1 - Depósito com valor zero
**Severidade (Baixa/Média/Alta):**  Baixa
**Prioridade (Baixa/Média/Alta):**  Baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O usuário consegue depositra 0, mesmo não sendo permitido.

**Passos para reproduzir:**  
1.  banco rodando
2.  criar conta
3.  depositar

**Resultado esperado:** Depositra apenas >0  
**Resultado obtido:**  Deposito = 0
**Evidência:**  Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0
**Impacto/Risco:**  Sem impactos ou riscos relevantes

## Template — Bug Report
**Título:**  falta de limite de caracteres no nome da conta
**Severidade (Baixa/Média/Alta):**  Alta
**Prioridade (Baixa/Média/Alta):**  Alta
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  ao criar uma conta pode-se colocar um numero indefinido de caracteres, ou seja, perigo grave no armazenamento e na memoria do sistema com usuarios mal intencionados

**Passos para reproduzir:**  
1.  inicia o banco
2.  utilize a função criar_usuario()
3.  parametro "String"*10^10000 e coloca quantos caracteres quiser.

**Resultado esperado:**  nome completo da pessoa
**Resultado obtido:**  bytes pseudo-infinitos
**Evidência:**  ao executar o codigo aparece <__main__.Conta at 0x7d67ed43fa40>
**Impacto/Risco:**  grande impacto e maximo risco, um unico usuario pode acabar com a aplicação

## Template — Bug Report
**Título:**  nome vazio ao criar a conta
**Severidade (Baixa/Média/Alta):**  média
**Prioridade (Baixa/Média/Alta):**  média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  bug ao criar uma conta sem identificação no nome

**Passos para reproduzir:**  
1.  inicia o banco
2.  banco.criar_conta()
3.  e passar o parametro "" string vazia

**Resultado esperado:**  fail
**Resultado obtido:**  pass
**Evidência:**  não ocorre erro ao criar
**Impacto/Risco:**  médio impacto e risco, pois não será possivel identificar o usuario

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)
print("bug de caracteres infinitos: ", Conta("Tony Stark"*100000000))
banco.depositar('tony', -1000000.00000001) # depositando numero negativo e com floats que não deviam
banco.depositar('tony', 21000000.00000001) # tanto negativos quanto positivos
banco.sacar('tony', 1/3) # e não tem limite de casas decimais especifica, então esta dizima passa
banco.transferir('pepper', 'tony stark', banco.contas['pepper'].saldo) # (é possivel até colocar todo o dinheiro da conta de um para o outro desta forma, mas não é algo controlavel pelo usuario, só achei legal a tentativa)
# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""