# -*- coding: utf-8 -*-
"""Atividade_QA_Banco_do_Stark_Thiago_de_Almeida_Brum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6clTPLk_G5PqIrdOwyczP60F_YLXHIi

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('--| Criar Conta |--')
banco.criar_conta('Ronaldo')
banco.criar_conta('Julio')
banco.criar_conta('Caio')

print('--| Deposito |--')
banco.depositar('Ronaldo', -1000)
banco.depositar('Julio', 500)

print('--| Saldo |--')
banco.saldo_atual('Ronaldo')
banco.saldo_atual('Julio')

print('--| Sacar |--')
banco.sacar('Julio', 200)
banco.saldo_atual('Ronaldo')

print('--| Transferir |--')
banco.transferir('Julio', 'Ronaldo', 100)

print('--| Saldo |--')
banco.saldo_atual('Ronaldo')
banco.saldo_atual('Julio')
banco.saldo_atual('Thiago')

print('--| Extrato |--')
banco.mostrar_extrato('Julio')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('\n Teste 01 - Criando registrando usuário sem nome')
banco.criar_conta('')

print('\n Teste 02 - Depositando um valor menor que zero')
banco.depositar('Julio', 1000)

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

print('\n Teste N7 - Transferência para si mesmo')
banco.transferir('Julio', 'Julio', 100)

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001

**Título/Objetivo:** CRIAR CONTA SEM NOME

**Pré-condição:** Banco Iniciado

**Passos:**  
1. Iniciar o Banco
2. banco.criarconta(' ')

**Resultado esperado:** ERROR - Você não pode criar uma conta sem nome.

**Resultado obtido:**  OK - Conta criada para:

**Status (Pass/Fail):** Fail

**Evidência:**

banco.criar_conta('')

Resultado: OK - Conta criada para:

## Template — Caso de Teste 2
**ID:** CT-002  

**Título/Objetivo:**  Depositando um valor negativo (< 0)

**Pré-condição:** Estar com o banco iniciado e já possuir uma conta instânciada.

**Passos:**  

1. Estar com o banco iniciado

2. Ter uma conta

3. Executar a função para depositar um valor negativo

**Resultado esperado:** ERROR - Você não pode depositar um valor <= 0

**Resultado obtido:**  OK - Depósito realizado: -1000

**Status (Pass/Fail):** Fail

**Evidência:**

banco.depositar('Ronaldo', -1000)

Resultado: OK - Depósito realizado: -1000

## Template — Caso de Teste 3
**ID:** CT-003  

**Título/Objetivo:**  Acessar um saldo de uma conta inexistente

**Pré-condição:**  Ter o banco iniciado e consultar uma conta inexistente

**Passos:**  

1.  Ter o banco iniciado

2.  Executar a função para consultar

**Resultado esperado:** ERRO - Conta não encontrada: Thiago

**Resultado obtido:**  ERRO - Conta não encontrada: Thiago

**Status (Pass/Fail):** Pass

**Evidência:** ERRO - Conta não encontrada: Thiago

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Depositar um valor negativo

**Severidade (Baixa/Média/Alta):**  Alta

**Prioridade (Baixa/Média/Alta):**  Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O usuário consegue depositar um valor negativo

**Passos para reproduzir:**  
1.  banco rodando
2.  executar a função para depositar passando um valor negativo

**Resultado esperado:** Você não pode depositar um valor <= 0

**Resultado obtido:**  OK - Depósito realizado: -1000

**Evidência:**
OK - Depósito realizado: -1000

**Impacto/Risco:** Um impacto muito alto.

## Template — Bug Report
**Título:** Criar uma conta sem nome

**Severidade (Baixa/Média/Alta):** Alta

**Prioridade (Baixa/Média/Alta):** Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** Criação de uma conta sem nome

**Passos para reproduzir:**  

1.  Ter o banco iniciado

2.  Executar a função para criar uma conta

3.  Passar um parâmetro vazio no nome

**Resultado esperado:**  ERROR - Você não pode criar uma conta sem nome

**Resultado obtido:** OK - Conta criada para:  

**Evidência:**  banco.criar_conta('')
OK - Conta criada para:

**Impacto/Risco:** O impacto é muito alto, pois existem métodos que dependem do nome para funcionar.

## Template — Bug Report
**Título:** Transferência para si mesmo

**Severidade (Baixa/Média/Alta):** Alta

**Prioridade (Baixa/Média/Alta):** Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O usuário consegue fazer uma transferência para si mesmo

**Passos para reproduzir:**  

1. Ter o banco iniciado

2. Executar a função para tranferir

3. Passar os parametros

**Resultado esperado:** ERROR - Você não pode transferir uma quantia para si mesmo

**Resultado obtido:** OK - Transferência realizada: 100

**Evidência:**  Teste N7 - Transferência para si mesmo

OK - Transferência realizada: 100  

**Impacto/Risco:**  Impacto alto, pois o funciona.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""