# -*- coding: utf-8 -*-
"""Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0l6atajzvE4g3JdQRKnxgN5ol80dCi0

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('byak')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 500)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 100)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES (QA)')
print('=================================\n')

print('\nValor inicial')
banco.saldo_atual('tony')

print('\nTeste N1 - Transferência para a própria conta')
banco.transferir('tony', 'tony', 100)

print('\nValor pós transferência')
banco.saldo_atual('tony')

print('\nTeste N2 - Saque negativo')
banco.sacar('tony', -100)

print('\nValor pós saque negativo')
banco.saldo_atual('tony')

print('\nTeste N3 - Depósito com valor decimal')
banco.depositar('tony', 10.45)

print('\nValor pós depósito')
banco.saldo_atual('tony')

print('\nTeste N3 - Depósito com texto')
banco.depositar('tony', 'Mil Reais')

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**   Tranferência para a própria conta

**Pré-condição:** Uma conta bancária existente no sistema para realizar a transferência.

**Passos:**  
1. Acessar a conta.
2. Realizar a transferência.

**Resultado esperado:** OK

**Resultado obtido:**  OK

**Status (Pass/Fail):** Pass

**Evidência:**

Teste N1 - Transferência para a própria conta
OK - Transferência realizada: 100

Valor pós transferência
SALDO tony = 300.0

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Saque negativo

**Pré-condição:** A conta deve possuir saldo disponível para saque (ex: R$100).
  
**Passos:**  
1.  Acessar a conta.
2.  Realizar o saque negativo.

**Resultado esperado:**  Erro

**Resultado obtido:**  Erro

**Status (Pass/Fail):**  Fail

**Evidência:**  
=== SAQUE ===

Teste N2 - Saque negativo

OK - Saque realizado: -100

Valor pós saque negativo

SALDO tony = 400.0

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Depósito com valor decimal

**Pré-condição:** Possuir uma conta no sistema.

**Passos:**  
1.  Realizar o depósito a uma conta existente.

**Resultado esperado:**  Ok

**Resultado obtido:**  OK

**Status (Pass/Fail):**  Pass

**Evidência:**  
Teste N3 - Depósito com valor decimal

OK - Depósito realizado: 10.45

Valor pós depósito

SALDO tony = 410.45

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Sistema permite saque com valor negativo e aumenta o saldo da conta

**Severidade (Baixa/Média/Alta):**  Alta

**Prioridade (Baixa/Média/Alta):**  Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O banco permite o usuário realizar saque negativo e, aumenta o saldo da conta

**Passos para reproduzir:**  
1.  Executar o sistema
2.  Verificar o saldo da conta
3.  Executar saque com valor negativo

**Resultado esperado:**  
O sistema deve rejeitar valor negativo e exibir mensagem de erro.

**Resultado obtido:**  
O sistema aceita o saque negativo e aumenta o saldo da conta.

**Evidência:**  
Teste N2 - Saque negativo
OK - Saque realizado: -100

Valor pós saque negativo
SALDO tony = 400.0

**Impacto/Risco:** Risco severo ao sistema podendo ter manipulação de saldo.

## Template — Bug Report
**Título:**  Sistema permite transferência para a própria conta

**Severidade (Baixa/Média/Alta):**  Média

**Prioridade (Baixa/Média/Alta):** Média

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  O sistema permite a transferência para a própria conta

**Passos para reproduzir:**  
1.  Executar o sistema
2.  Criar a conta
3.  Realizar a transferência da conta 1 para a conta 1

**Resultado esperado:** O sistema deve bloquear transferências para a mesma conta e exibir uma mensagem de erro.

**Resultado obtido:**  
O sistema permite a transferência.

**Evidência:**  
Teste N1 - Transferência para a própria conta

OK - Transferência realizada: 100

**Impacto/Risco:**  Transferências para si mesmo gera inconsistência no extrato

## Template — Bug Report
**Título:**  Sistema não valida tipo de valor no depósito e gera erro de execução

**Severidade (Baixa/Média/Alta):**  Alta

**Prioridade (Baixa/Média/Alta):**  Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O ambiente gera erro na execução e trava, não apresentando mensagem de erro e notificando o usuário

**Passos para reproduzir:**  
1.  Executar o sistema
2.  Criar uma conta
3.  Executar a transferência com 'Mil Reais'

**Resultado esperado:**
O sistema deve validar a entrada e exibir uma mensagem informando que o valor do depósito deve ser numérico.

**Resultado obtido:**  
O sistema gera erro de execução TypeError e interrompe o programa.

**Evidência:**  
Teste N3 - Depósito com texto

TypeError: unsupported operand type(s) for +=: 'float' and 'str'

**Impacto/Risco:**  
O sistema pode interromper a execução caso receba entradas inválidas, afetando a estabilidade da aplicação.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""