# -*- coding: utf-8 -*-
"""ViniciusXavierFontes106533Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8dW_iJbDQwQ17XY8iVnKQ2STi0U4kY1

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO DE TESTES (QA)
# =========================================

print('=== CRIAR CONTAS DE TESTE ===')
banco.criar_conta('steve')
banco.criar_conta('clint')
banco.criar_conta('wanda')

print('\n=== TESTE POSITIVO P1 - Depósito válido ===')
banco.depositar('steve', 300)
banco.saldo_atual('steve')

print('\n=== TESTE POSITIVO P2 - Saque com saldo suficiente ===')
banco.sacar('steve', 100)
banco.saldo_atual('steve')

print('\n=== TESTE POSITIVO P3 - Múltiplas operações ===')
banco.depositar('clint', 200)
banco.depositar('clint', 50)
banco.sacar('clint', 30)
banco.saldo_atual('clint')

print('\n=== TESTE POSITIVO P4 - Transferência válida ===')
banco.transferir('steve', 'wanda', 50)
banco.saldo_atual('steve')
banco.saldo_atual('wanda')

print('\n=== EXTRATO (steve) ===')
banco.mostrar_extrato('steve')


print('\n=================================')
print(' TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com texto')
try:
    banco.depositar('steve', "cem")
except Exception as e:
    print("Erro detectado:", e)

print('\nTeste N2 - Saque com valor negativo')
banco.sacar('clint', -40)

print('\nSaldo após tentativa de saque negativo')
banco.saldo_atual('clint')

print('\nTeste N3 - Saque em conta sem saldo')
banco.sacar('wanda', 500)

print('\nTeste N4 - Transferência com valor negativo')
banco.transferir('steve', 'wanda', -20)

print('\nTeste N5 - Depósito em conta inexistente')
banco.depositar('loki', 100)

print('\nTeste N6 - Transferência de conta inexistente')
banco.transferir('loki', 'steve', 50)

"""# Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

##CASO 1
**ID: CT-001**

**Título/Objetivo:** Depósito com valor válido

**Pré-condição:** Banco Iniciado



**Passos:**

Criar conta steve

Realizar depósito de 300

Consultar saldo da conta

**Resultado esperado:**
Saldo atualizado para 300 após o depósito.

**Resultado obtido:**
OK - Depósito realizado: 300
SALDO steve = 300.0

**Status (Pass/Fail):** Pass

**Evidência:**

=== TESTE POSITIVO P1 - Depósito válido ===
OK - Depósito realizado: 300
SALDO steve = 300.0

##CASO 2
**ID: CT-002**

**Título/Objetivo:** Saque com saldo suficiente

**Pré-condição:** Banco iniciado e conta com saldo disponível

**Passos:**

Criar conta steve

Depositar 300

Sacar 100

**Resultado esperado:**
Saque realizado com sucesso e saldo atualizado para 200.

**Resultado obtido:**
OK - Saque realizado: 100
SALDO steve = 200.0

**Status (Pass/Fail):** Pass

**Evidência:**


=== TESTE POSITIVO P2 - Saque com saldo suficiente ===
OK - Saque realizado: 100
SALDO steve = 200.0

##CASO 3
**ID: CT-003**

**Título/Objetivo:** Saque com valor negativo

**Pré-condição:** Banco iniciado e conta com saldo disponível

**Passos:**

Criar conta clint

Depositar 200

Realizar saque de -40

**Resultado esperado:**
O sistema deveria bloquear a operação.

**Resultado obtido:**
OK - Saque realizado: -40
SALDO clint = 260.0

**Status (Pass/Fail):** Fail

**Evidência:**


Teste N2 - Saque com valor negativo
OK - Saque realizado: -40

Saldo após tentativa de saque negativo
SALDO clint = 260.0

# Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

##Bug Report 1

**Título:** Teste N2 - Saque com valor negativo

**Severidade (Baixa/Média/Alta):** Alta

**Prioridade (Baixa/Média/Alta):** Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark

**Descrição:**
O usuário consegue realizar saque com valor negativo, o que faz o saldo da conta aumentar.

**Passos para reproduzir:**

banco rodando
criar conta
depositar valor positivo
realizar saque negativo

**Resultado esperado:**
Sistema deve aceitar apenas valores positivos para saque.

**Resultado obtido:**
OK - Saque realizado: -40

**Evidência:**

Teste N2 - Saque com valor negativo
OK - Saque realizado: -40

Saldo após tentativa de saque negativo
SALDO clint = 260.0






**Impacto/Risco:**
Pode permitir manipulação incorreta do saldo da conta.

##Bug Report 2

**Título:** Teste N4 - Transferência com valor negativo

**Severidade (Baixa/Média/Alta):** Alta

**Prioridade (Baixa/Média/Alta):** Alta

**Ambiente:** Google Colab / Python 3.x / Banco do Stark

**Descrição:**
O sistema permite realizar transferência com valor negativo entre contas.

**Passos para reproduzir:**

banco rodando
criar conta origem
criar conta destino
realizar transferência com valor negativo

**Resultado esperado:**
Sistema deveria permitir apenas valores positivos.

**Resultado obtido:**
OK - Transferência realizada: -20

**Evidência:**

Teste N4 - Transferência com valor negativo
OK - Transferência realizada: -20

**Impacto/Risco:**
Pode causar inconsistência nos saldos das contas.

##Bug Report 3

**Título:** Teste N1 - Depósito com valor texto

**Severidade (Baixa/Média/Alta):**  Média

**Prioridade (Baixa/Média/Alta):**  Média

**Ambiente:**  Google Colab / Python 3.x / Banco do Stark

**Descrição:**
Ao tentar realizar um depósito com texto, o sistema apresenta erro de execução.

**Passos para reproduzir:**

banco rodando
criar conta
tentar depositar texto

**Resultado esperado:**
Sistema deveria mostrar mensagem informando que apenas números são permitidos.

**Resultado obtido:**
Erro detectado: unsupported operand type(s) for +=: 'float' and 'str'

**Evidência:**

Teste N1 - Depósito com texto
Erro detectado: unsupported operand type(s) for +=: 'float' and 'str'


**Impacto/Risco:**
Pode interromper a execução do sistema e gerar falhas na aplicação.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""