# -*- coding: utf-8 -*-
"""EXERCICIO_AULA_13_03_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeQkXSDhJjV3njnC-ji5QCNY-yQLaWz9
"""



"""Atividade Prática — QA com APIs (SWAPI)
Versão do aluno — com scripts base
Tempo estimado: 60 minutos
Ferramenta: Google Colab
Formato: em grupos de 2 a 4 componentes ou, se preferirem, individualmente.
Objetivo: investigar respostas de uma API, ajustar scripts simples e responder às perguntas como um QA.

Instruções
Nesta atividade, vocês não precisam criar tudo do zero.
Os scripts já estão prontos como base. A tarefa do grupo será:

Executar os blocos de código
Alterar apenas o que for pedido
Observar os resultados
Responder às perguntas em Markdown
Discutir em grupo quais validações um QA faria
Entrega
Cada grupo pode entregar um único notebook com:

nomes dos integrantes
respostas das perguntas
scripts ajustados
asserts completados
Se alguém optar por fazer sozinho, pode entregar individualmente sem problema.
"""



import requests
import json

# -------------------------
# MODO DE SEGURANÇA (fallback)
# -------------------------
# Se a API não responder, o notebook usa dados locais
# para a atividade continuar funcionando.

DADOS_FALLBACK = {
    "https://swapi.dev/api/people/10/": {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "eye_color": "blue-gray",
        "gender": "male",
        "url": "https://swapi.dev/api/people/10/"
    },
    "https://swapi.dev/api/people/13/": {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "eye_color": "blue",
        "gender": "male",
        "url": "https://swapi.dev/api/people/13/"
    },
    "https://swapi.dev/api/planets/2/": {
        "name": "Alderaan",
        "climate": "temperate",
        "terrain": "grasslands, mountains",
        "population": "2000000000",
        "url": "https://swapi.dev/api/planets/2/"
    },
    "https://swapi.dev/api/starships/10/": {
        "name": "Millennium Falcon",
        "model": "YT-1300 light freighter",
        "manufacturer": "Corellian Engineering Corporation",
        "max_atmosphering_speed": "1050",
        "url": "https://swapi.dev/api/starships/10/"
    }
}

class RespostaLocal:
    def __init__(self, status_code, data):
        self.status_code = status_code
        self._data = data
        self.text = json.dumps(data, ensure_ascii=False)

    def json(self):
        return self._data

def buscar_endpoint(url):
    try:
        resposta = requests.get(url, timeout=10)
        if resposta.status_code == 200:
            return resposta, "online"
    except Exception:
        pass

    if url in DADOS_FALLBACK:
        return RespostaLocal(200, DADOS_FALLBACK[url]), "fallback local"

    return RespostaLocal(404, {"detail": "Not found"}), "fallback local"

print("Ambiente preparado com sucesso.")

"""Identificação do grupo


   Integrante 1:

Integrante 2:

Integrante 3 (se houver):

Integrante 4 (se houver):




Parte 1 — Explorando a API

Nesta primeira parte, vocês vão consultar 4 endpoints.

O trabalho do grupo será alterar apenas a URL em cada bloco, executar e observar o retorno.




1.1 Personagem 22


Tarefa: execute o script e observe:

status code


nome

altura

cor dos olhos

### 1.1 Personagem 22
"""

url = "https://swapi.dev/api/people/22/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""Personagem: 22


Status code: 200

Nome do personagem: Boba Fett

Altura: 183

Cor dos olhos: Marrom

O JSON parece completo? Sim

### 1.2 Personagem 33
"""

url = "https://swapi.dev/api/people/33/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""Personagem: 33


Status code: 200

Nome do personagem: Nute Gunray

Altura: 191

Cor dos olhos: vermelho

O JSON parece completo? Sim

### 1.3 Personagem 39
"""

url = "https://swapi.dev/api/people/39/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""Personagem: 39


Status code: 200

Nome do personagem: Ric Olié

Altura: 183

Cor dos olhos: azul

O JSON parece completo? Sim

### 1.4 Personagem 52
"""

url = "https://swapi.dev/api/people/52/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""Personagem: 52


Status code: 200

Nome do personagem: Ki-Adi-Mundi

Altura: 198

Cor dos olhos: unknown - amarelo

O JSON parece completo? Sim
"""

url = "https://swapi.dev/api/planets/5/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""### 2.1 Planeta 5




"""

url = "https://swapi.dev/api/planets/5/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""Planeta 5

- Status code: 200

- Nome do planeta: Dagobah

- Clima: Turbulento

- Terreno: pântano, florestas

- População: desconhecida

- O JSON parece completo? Sim

### 2.2 Nave 15
"""

url = "https://swapi.dev/api/starships/15/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Tarefa:** execute o bloco e observe:

- Status code: 200

- nome da nave: Executo

- modelo: Supercorde Executor

- fabricante: Estaleiros Kuat,

- velocidade máxima em atmosfera: n/a

- O JSON parece completo? Sim

## Parte 2 — Extraindo campos específicos

Agora você vai executar os scripts e **completar as respostas**.

### 2.1 Extraindo campos do personagem




**Tarefa:** execute o bloco e depois responda.
"""

url = "https://swapi.dev/api/people/5/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome:", dados["name"])
print("Altura:", dados["height"])
print("Cor dos olhos:", dados["eye_color"])
print("Gênero:", dados["gender"])

"""Qual campo foi usado para mostrar o nome?
## dados["name"]


Qual campo foi usado para mostrar a altura?
## dados["height"]


Se você fosse QA, quais desses campos validaria primeiro?
## Eu validaria primeiro o campo name, pois ele identifica o personagem retornado pela API e permite confirmar se o endpoint trouxe o personagem correto.

### 2.2 Extraindo campos do planeta

**Tarefa:** execute o bloco e complete as respostas.
"""

url = "https://swapi.dev/api/planets/12/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome do planeta:", dados["name"])
print("Clima:", dados["climate"])
print("Terreno:", dados["terrain"])
print("População:", dados["population"])

"""1. O campo população parece numérico?
## Sim



2. O clima foi retornado corretamente?
## Sim


3. Se você fosse QA, o que validaria nesse planeta?
## Eu validaria se os campos principais como name, climate, terrain e population estão presentes no JSON e se os valores retornados correspondem corretamente ao planeta Utapau na Star Wars API.

## Parte 3 — Pensando como QA

Agora você vai trabalhar com validações simples.

### 3.1 Validações básicas

**Tarefa:** execute o bloco abaixo e depois escreva o que cada validação verifica.
"""

url = "https://swapi.dev/api/people/5/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Validação 1 - status 200:", response.status_code == 200)
print("Validação 2 - campo 'name' existe:", "name" in dados)
print("Validação 3 - nome não está vazio:", dados["name"] != "")
print("Validação 4 - campo 'height' existe:", "height" in dados)

"""1. O que a validação 1 verifica?
## Verifica se o status da requisição é 200, indicando que a API respondeu com sucesso.


2. O que a validação 2 verifica?
## Verifica se o campo name existe no JSON retornado pela API.


3. O que a validação 3 verifica?
## Verifica se o campo name não está vazio, garantindo que o personagem possui um nome válido.


4. O que a validação 4 verifica?
## Verifica se o campo height existe no JSON, confirmando que a informação de altura está presente na resposta.

### 3.2 Complete as validações

**Tarefa:** execute o bloco abaixo. Ele já está funcionando. Depois, alterem as expressões se o professor pedir outra nave ou outro endpoint. Em seguida, expliquem por que cada validação faz sentido para QA.
"""

url = "https://swapi.dev/api/starships/15/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Status 200:", response.status_code == 200)

# Os exemplos abaixo já estão corretos e executáveis.
# Se o professor pedir, vocês podem alterar para validar outros campos.
print("Campo 'name' existe:", "name" in dados)
print("Campo 'model' existe:", "model" in dados)
print("Nome não está vazio:", dados["name"] != "")

"""## Parte 4 — Testes automatizados com assert

Agora vocês vão trabalhar sobre scripts já prontos. Os asserts abaixo já executam sem erro. A tarefa do grupo é **entender o que cada linha valida**, ajustar se o professor pedir outro recurso e registrar as respostas.

### 4.1 Assert no personagem

**Tarefa:** execute o bloco. Depois, expliquem o que cada assert valida e, se quiserem, alterem o endpoint para outro personagem.
"""

url = "https://swapi.dev/api/people/5/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "name" in dados, "Erro: campo name não encontrado"
assert dados["name"] != "", "Erro: nome vazio"

print("Todos os testes do personagem passaram!")

"""assert response.status_code == 200
Verifica se a requisição para a API foi realizada com sucesso. O código 200 indica que o servidor respondeu corretamente.



assert "name" in dados
Verifica se o campo name existe no JSON retornado pela API.


assert dados["name"] != ""
Verifica se o campo name não está vazio, garantindo que o personagem possui um nome válido.

### 4.2 Assert na nave

**Tarefa:** execute o bloco. Depois, descrevam qual campo foi validado em cada assert e proponham mais 1 validação extra em Markdown.
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "manufacturer" in dados, "Erro: fabricante não encontrado"
assert dados["model"] != "", "Erro: modelo vazio"

print("Todos os testes da nave passaram!")

"""Assert 1:
Valida o status da requisição (status_code), verificando se o valor é 200.



Assert 2:
Valida se o campo manufacturer existe no JSON retornado pela API.



Assert 3:
Valida se o campo model não está vazio.
"""

url = "https://swapi.dev/api/starships/15/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "manufacturer" in dados, "Erro: fabricante não encontrado"
assert dados["model"] != "", "Erro: modelo vazio"

print("Todos os testes da nave passaram!")

"""## Parte 5 — Cenário negativo

Agora você vai observar como a API se comporta quando pedimos um recurso inexistente.
"""

url = "https://swapi.dev/api/people/5555/"
response, origem = buscar_endpoint(url)

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print("Texto retornado:")
print(response.text)

"""1. Qual status code foi retornado?
Foi retornado o status code 404, indicando que o recurso solicitado não foi encontrado.


2. Esse comportamento está correto?
Sim, esse comportamento está correto, pois a API deve retornar 404 quando o recurso solicitado não existe.


3. Por que um QA deve testar cenários negativos?
Porque é importante verificar como o sistema se comporta quando ocorre um erro ou quando um recurso inexistente é solicitado, garantindo que a API responda corretamente e que o sistema trate esses casos de forma adequada.

## Parte 6 — Mini desafio final

Agora você vai alterar apenas o endpoint da função abaixo e gerar um pequeno resumo.
"""

def resumo_recurso(url):
    response, origem = buscar_endpoint(url)
    print("Origem dos dados:", origem)
    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Recurso não encontrado.")
        return

    dados = response.json()

    for chave, valor in dados.items():
        print(f"{chave}: {valor}")

# ALTERE O ENDPOINT ABAIXO PARA TESTAR OUTRO RECURSO
resumo_recurso("https://swapi.dev/api/planets/5/")

"""1. Qual endpoint você testou no desafio?

"https://swapi.dev/api/planets/5/"


2. Qual foi o status code?

O status code retornado foi 200, indicando que a requisição foi realizada com sucesso.


3. Qual campo chamou mais a sua atenção?

O campo climate, pois ele mostra as características ambientais do planeta.


4. Se você fosse QA, quais 3 validações faria nesse recurso?

Validaria se o status code é 200 para garantir que a requisição foi bem-sucedida.

Validaria se os campos principais como name, climate e terrain existem no JSON retornado.

Validaria se o campo population possui um valor válido e não está vazio.


"""