# -*- coding: utf-8 -*-
"""Samuel_Estevão_Erlan_Souza_ QA_SWAPI_atividade_grupo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpTqDIGudIEDutQQHdE6ed35Lv46m_md

# Atividade Prática — QA com APIs (SWAPI)

## Versão do aluno — com scripts base

**Tempo estimado:** 60 minutos  
**Ferramenta:** Google Colab  
**Formato:** em grupos de **2 a 4 componentes** ou, se preferirem, **individualmente**.  
**Objetivo:** investigar respostas de uma API, ajustar scripts simples e responder às perguntas como um QA.

### Instruções
Nesta atividade, vocês **não precisam criar tudo do zero**.  
Os scripts já estão prontos como base. A tarefa do grupo será:

1. **Executar** os blocos de código
2. **Alterar apenas o que for pedido**
3. **Observar os resultados**
4. **Responder às perguntas em Markdown**
5. **Discutir em grupo** quais validações um QA faria

### Entrega
Cada grupo pode entregar **um único notebook** com:
- nomes dos integrantes
- respostas das perguntas
- scripts ajustados
- asserts completados

Se alguém optar por fazer sozinho, pode entregar individualmente sem problema.
"""

import requests
import json

# -------------------------
# MODO DE SEGURANÇA (fallback)
# -------------------------
# Se a API não responder, o notebook usa dados locais
# para a atividade continuar funcionando.

DADOS_FALLBACK = {
    "https://swapi.dev/api/people/10/": {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "eye_color": "blue-gray",
        "gender": "male",
        "url": "https://swapi.dev/api/people/10/"
    },
    "https://swapi.dev/api/people/13/": {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "eye_color": "blue",
        "gender": "male",
        "url": "https://swapi.dev/api/people/13/"
    },
    "https://swapi.dev/api/planets/2/": {
        "name": "Alderaan",
        "climate": "temperate",
        "terrain": "grasslands, mountains",
        "population": "2000000000",
        "url": "https://swapi.dev/api/planets/2/"
    },
    "https://swapi.dev/api/starships/10/": {
        "name": "Millennium Falcon",
        "model": "YT-1300 light freighter",
        "manufacturer": "Corellian Engineering Corporation",
        "max_atmosphering_speed": "1050",
        "url": "https://swapi.dev/api/starships/10/"
    }
}

class RespostaLocal:
    def __init__(self, status_code, data):
        self.status_code = status_code
        self._data = data
        self.text = json.dumps(data, ensure_ascii=False)

    def json(self):
        return self._data

def buscar_endpoint(url):
    try:
        resposta = requests.get(url, timeout=10)
        if resposta.status_code == 200:
            return resposta, "online"
    except Exception:
        pass

    if url in DADOS_FALLBACK:
        return RespostaLocal(200, DADOS_FALLBACK[url]), "fallback local"

    return RespostaLocal(404, {"detail": "Not found"}), "fallback local"

print("Ambiente preparado com sucesso.")

"""## Identificação do grupo

- Integrante 1:Samuel Estevão
- Integrante 2:Erlan Santos
- Integrante 3 (se houver):
- Integrante 4 (se houver):

## Parte 1 — Explorando a API

Nesta primeira parte, vocês vão consultar 4 endpoints.  
O trabalho do grupo será **alterar apenas a URL** em cada bloco, executar e observar o retorno.

### 1.1 Personagem 4

**Tarefa:** execute o script e observe:
- status code 200
- nome Darth Vader
- altura 202
- cor dos olhos yellow
"""

url = "https://swapi.dev/api/people/4/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""### 1.2 Personagem 67

**Tarefa:** neste bloco, troque apenas o endpoint se necessário, execute e observe o retorno.

**Respostas do aluno — Personagem 67**

- Status code: 200
- Nome do personagem: Dooku
- Altura: 193
- Cor dos olhos: brown
- O JSON parece completo? sim
"""

url = "https://swapi.dev/api/people/67/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

url = "https://swapi.dev/api/people/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 13**

- Status code: 200
- Nome do personagem:Chewbacca
- Altura:228
- Cor dos olhos:blue
- O JSON parece completo?sim

### 1.3 Planeta 1

**Tarefa:** execute o bloco e observe:
- nome do planeta:  Tatooine
- clima: arid
- terreno: desert
- população: 200000
"""

url = "https://swapi.dev/api/planets/1/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Planeta 12**

- Status code: 200
- Nome do planeta: Utapau
- Clima: temperate, arid, windy",
- Terreno:scrublands, savanna, canyons, sinkholes"
- População:95000000
- O JSON parece completo? Sim
"""

url = "https://swapi.dev/api/planets/12/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""### 1.4 Nave 15 resposta

**Tarefa:** execute o bloco e observe:
- nome da nave: Executor
- modelo: Executor-class star dreadnought
- fabricante: uat Drive Yards, Fondor Shipyards
- velocidade máxima em atmosfera: n/a
- O JSON parece completo? Sim
"""

url = "https://swapi.dev/api/starships/15/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""## Parte 2 — Extraindo campos específicos

Agora você vai executar os scripts e **completar as respostas**.

### 2.1 Extraindo campos do personagem

**Tarefa:** execute o bloco e depois responda.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome:", dados["name"])
print("Altura:", dados["height"])
print("Cor dos olhos:", dados["eye_color"])
print("Gênero:", dados["gender"])

"""**Perguntas**
1. Qual campo foi usado para mostrar o nome? name
2. Qual campo foi usado para mostrar a altura? height
3. Se você fosse QA, quais desses campos validaria primeiro?

  1° o name: pois é um campo principal de identificação do personagem, então precisa estar correto e não pode vir vazio.
 depois o peso verficando se esá presente ou apresentando algum erro.

### 2.2 Extraindo campos do planeta

**Tarefa:** execute o bloco e complete as respostas.
"""

url = "https://swapi.dev/api/planets/6/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome do planeta:", dados["name"])
print("Clima:", dados["climate"])
print("Terreno:", dados["terrain"])
print("População:", dados["population"])

"""**Perguntas**
1. O campo população parece numérico? Sim
2. O clima foi retornado corretamente? sim
3. Se você fosse QA, o que validaria nesse planeta?<BR>
name: se o nome do planeta está correto e não está vazio.<BR>
climate:  se o clima vem preenchido e em formato válido.<BR>
terrain: se o terreno está listado corretamente.<BR>
population:  se a população é um número válido ou valor esperado da API.

## Parte 3 — Pensando como QA

Agora você vai trabalhar com validações simples.

### 3.1 Validações básicas

**Tarefa:** execute o bloco abaixo e depois escreva o que cada validação verifica.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Validação 1 - status 200:", response.status_code == 200)
print("Validação 2 - campo 'name' existe:", "name" in dados)
print("Validação 3 - nome não está vazio:", dados["name"] != "")
print("Validação 4 - campo 'height' existe:", "height" in dados)

"""**Explique com suas palavras**
1. O que a validação 1 verifica? Status de rota/requisição
2. O que a validação 2 verifica? verifica se o campo "name" existe na resposta da API.
3. O que a validação 3 verifica? verifica se o nome está vazio
4. O que a validação 4 verifica? verifica se o campo "height" existe na resposta da API.

### 3.2 Complete as validações

**Tarefa:** execute o bloco abaixo. Ele já está funcionando. Depois, alterem as expressões se o professor pedir outra nave ou outro endpoint. Em seguida, expliquem por que cada validação faz sentido para QA.
"""

url = "https://swapi.dev/api/starships/15/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Status 200:", response.status_code == 200)

# Os exemplos abaixo já estão corretos e executáveis.
# Se o professor pedir, vocês podem alterar para validar outros campos.
print("Campo 'name' existe:", "name" in dados)
print("Campo 'model' existe:", "model" in dados)
print("Nome não está vazio:", dados["name"] != "")

"""**Resposta**<br>
Status 200: verifica se a requisição para a API foi bem-sucedida e se o endpoint está funcionando corretamente.

Campo name existe: garante que a resposta da API contém o campo de nome da nave, que é uma informação importante do recurso.

Campo model existe: verifica se o modelo da nave está presente na resposta, garantindo que a estrutura do JSON está correta.

Nome não está vazio: valida que o campo name possui um valor, evitando dados vazios ou incompletos retornados pela API.

## Parte 4 — Testes automatizados com assert

Agora vocês vão trabalhar sobre scripts já prontos. Os asserts abaixo já executam sem erro. A tarefa do grupo é **entender o que cada linha valida**, ajustar se o professor pedir outro recurso e registrar as respostas.

### 4.1 Assert no personagem

**Tarefa:** execute o bloco. Depois, expliquem o que cada assert valida e, se quiserem, alterem o endpoint para outro personagem.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "name" in dados, "Erro: campo name não encontrado"
assert dados["name"] != "", "Erro: nome vazio"

print("Todos os testes do personagem passaram!")

"""**resposta**:
assert response.status_code == 200
Verifica se a requisição para a API foi bem-sucedida. Se o status for diferente de 200, significa que houve erro na rota ou no servidor.

assert "name" in dados
Valida se o campo name existe na resposta da API. Isso garante que a estrutura do JSON retornado está correta.

assert dados["name"] != ""
Verifica se o campo name não está vazio, garantindo que a API retornou um dado válido.

### 4.2 Assert na nave

**Tarefa:** execute o bloco. Depois, descrevam qual campo foi validado em cada assert e proponham mais 1 validação extra em Markdown.
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "manufacturer" in dados, "Erro: fabricante não encontrado"
assert dados["model"] != "", "Erro: modelo vazio"
##validação extra##
assert "name" in dados, "Erro: nome da nave não encontrado"
print("Todos os testes da nave passaram!")

"""**respostas:**<br>
assert response.status_code == 200
Valida se a requisição para a API foi bem-sucedida (status 200), indicando que o endpoint está funcionando corretamente.

assert "manufacturer" in dados
Verifica se o campo manufacturer (fabricante da nave) existe na resposta da API.

assert dados["model"] != ""
Valida se o campo model (modelo da nave) não está vazio, garantindo que a API retornou um valor válido.<br>

**validação extra**<br>
assert "name" in dados, "Erro: nome da nave não encontrado"

Essa validação verifica se o campo name existe, garantindo que a resposta da API contém o nome da nave, que é uma informação importante do recurso.

## Parte 5 — Cenário negativo

Agora você vai observar como a API se comporta quando pedimos um recurso inexistente.
"""

url = "https://swapi.dev/api/people/9999/"
response, origem = buscar_endpoint(url)

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print("Texto retornado:")
print(response.text)

"""**Perguntas**
1. Qual status code foi retornado? 404
2. Esse comportamento está correto? sim
3. Por que um QA deve testar cenários negativos?

para ver se o sistema lida bem com erros e responde corretamente quando algo inválido acontece.

## Parte 6 — Mini desafio final

Agora você vai alterar apenas o endpoint da função abaixo e gerar um pequeno resumo.
"""

def resumo_recurso(url):
    response, origem = buscar_endpoint(url)
    print("Origem dos dados:", origem)
    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Recurso não encontrado.")
        return

    dados = response.json()

    for chave, valor in dados.items():
        print(f"{chave}: {valor}")

# ALTERE O ENDPOINT ABAIXO PARA TESTAR OUTRO RECURSO
resumo_recurso("https://swapi.dev/api/planets/9/")

"""**Respostas finais**
1. Qual endpoint você testou no desafio? 9
2. Qual foi o status code? 200
3. Qual campo chamou mais a sua atenção? name
4. Se você fosse QA, quais 3 validações faria nesse recurso?<br>
Verificar se o status code é 200.<br>
Verificar se o campo name existe e não está vazio.<br>
Verificar se o campo population existe e tem um valor válido.

# Entrega da atividade

Entreguem:

1. O notebook preenchido  
2. As respostas em Markdown  
3. Os scripts ajustados  
4. Os asserts analisados e/ou adaptados  
5. Uma conclusão curta do grupo: **quais foram as 3 validações mais importantes?**

## Fechamento
Ao final desta atividade, vocês praticaram:

- leitura de resposta JSON
- análise de status code
- validação de campos
- pensamento de QA
- testes simples com assert
- análise de cenário negativo
"""